### ISSUE TITLE
I can't  login with a demo account.

### ISSUE THREAD

**Issue by alemioma** [guncebektas/ElvinCMS#3]
Hallo Tekin!

Thank you in advance for the project! 
I went throught all the steps and after the installation I could not login with a demo account. I click i the link but the app say:

> These  credentials do not match our records. 

> 
Any idea about what to do in order to get access to the application?

**Comment by guncebektas** [comment]
probably you don't have any user account in your database, please sign up and update role_id to 1 in the users table. Then, login with the account. @alemioma

**Comment by tekinerten** [comment]
when you sign up, you are only a user and can't redirect admin page. your default role_id is 4 in **users** table. you should look up **roles** table. change your role_id according to **roles** table as Günce mentioned.
